# Site settings
title: adaept
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hyde away from Jekyll...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adaept.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  peterennis
highlighter: rouge
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
